"use client";
import {useEffect,useMemo,useState} from "react";
import ReportForm from "./ReportForm";
import {demoReports} from "@/lib/demo";
import {statusLabel,type Report,type Role,type Status} from "@/lib/types";
import {isConfigured} from "@/lib/supabase";
import jsPDF from "jspdf";
type Page="login"|"home"|"new"|"attach"|"confirm"|"reports"|"detail"|"review"|"admin"|"alerts"|"profile";
type Alert={id:string;kind:"revision"|"approved"|"submitted";title:string;message:string;time:string;read:boolean};
const demoAlerts:Alert[]=[{id:"a1",kind:"revision",title:"보완 요청",message:"문제 사항에 예상 완료 시간을 추가해 주세요.",time:"5분 전",read:false},{id:"a2",kind:"approved",title:"승인 완료",message:"제출한 보고서가 승인되었습니다.",time:"1시간 전",read:false},{id:"a3",kind:"submitted",title:"제출 완료",message:"보고서가 정상적으로 제출되었습니다.",time:"2시간 전",read:true}];
function Header({title,sub,onBack}:{title:string;sub?:string;onBack?:()=>void}){return <header className="top compact">{onBack&&<button className="back" onClick={onBack}>←</button>}<h1>{title}</h1>{sub&&<p>{sub}</p>}</header>}
function BottomNav({page,role,onGo}:{page:Page;role:Role;onGo:(p:Page)=>void}){const items:[Page,string][]=[["home","⌂ 홈"],["new","＋ 작성"],["reports","▤ 보고서"],["alerts","● 알림"],[role==="admin"?"admin":"profile",role==="admin"?"⚙ 관리":"♙ 내 정보"]];return <nav className="nav">{items.map(([p,l])=><button key={p} className={page===p?"active":""} onClick={()=>onGo(p)}>{l}</button>)}</nav>}
function Badge({status}:{status:Status}){return <span className={`badge ${status}`}>{statusLabel[status]}</span>}
export default function App(){
 const [page,setPage]=useState<Page>("login");const [role,setRole]=useState<Role>("employee");const [reports,setReports]=useState<Report[]>(demoReports);const [selected,setSelected]=useState<Report|null>(null);const [pending,setPending]=useState<Report|null>(null);const [alerts,setAlerts]=useState(demoAlerts);const [files,setFiles]=useState<string[]>([]);const [ready,setReady]=useState(false);
 useEffect(()=>{try{const saved=localStorage.getItem("smart-daily-reports");if(saved)setReports(JSON.parse(saved))}finally{setReady(true)}},[]);
 useEffect(()=>{if(ready)localStorage.setItem("smart-daily-reports",JSON.stringify(reports))},[reports,ready]);
 const counts=useMemo(()=>({submitted:reports.filter(r=>r.status==="submitted").length,revision:reports.filter(r=>r.status==="revision_requested").length,approved:reports.filter(r=>r.status==="approved").length}),[reports]);
 function saveDraft(r:Report){setReports(x=>[r,...x.filter(i=>i.id!==r.id)]);setPage("reports")}
 function stage(r:Report){if(r.status==="draft"){saveDraft(r);return}setPending(r);setPage("attach")}
 function submit(){if(!pending)return;const r={...pending,status:"submitted" as const};setReports(x=>[r,...x.filter(i=>i.id!==r.id)]);setAlerts(x=>[{id:crypto.randomUUID(),kind:"submitted",title:"제출 완료",message:`${r.title} 보고서가 제출되었습니다.`,time:"방금",read:false},...x]);setPending(null);setFiles([]);setPage("home")}
 function decide(status:"approved"|"revision_requested"){if(!selected)return;const feedback=status==="approved"?"확인했습니다. 수고하셨습니다.":"문제 사항에 예상 완료 시간을 추가해 주세요.";setReports(x=>x.map(r=>r.id===selected.id?{...r,status,feedback}:r));setAlerts(x=>[{id:crypto.randomUUID(),kind:status==="approved"?"approved":"revision",title:status==="approved"?"승인 완료":"보완 요청",message:feedback,time:"방금",read:false},...x]);setPage("reports")}
 function open(r:Report){setSelected(r);setPage(role==="leader"||role==="admin"?"review":"detail")}
 function pdf(r:Report){const d=new jsPDF();d.setFontSize(18);d.text("Smart Daily Work Report",20,20);d.setFontSize(11);[r.work_date,r.title,`${r.author_name} / ${r.department}`,`Progress ${r.progress}%`,`Status ${statusLabel[r.status]}`].forEach((t,i)=>d.text(t,20,38+i*9));d.save(`daily-report-${r.work_date}.pdf`)}
 if(page==="login")return <main className="login-page"><section className="login-hero"><div className="shield">✓</div><h1>스마트 일일 업무</h1><p>오늘의 업무를 빠르고 정확하게 공유하세요.</p></section><section className="login-card"><label>이메일<input defaultValue="demo@company.co.kr"/></label><label>비밀번호<input type="password" defaultValue="12345678"/></label><label>데모 역할<select value={role} onChange={e=>setRole(e.target.value as Role)}><option value="employee">직원</option><option value="leader">팀장</option><option value="admin">관리자</option></select></label><button className="primary wide" onClick={()=>setPage(role==="admin"?"admin":"home")}>로그인</button><button className="text-button">비밀번호를 잊으셨나요?</button></section></main>;
 if(page==="new")return <ReportForm initial={pending??undefined} onSave={stage} onCancel={()=>setPage("home")}/>;
 if(page==="attach")return <main className="shell"><Header title="사진·문서 첨부" onBack={()=>setPage("new")}/><section className="card space"><div className="notice orange">최대 5개, 파일당 10MB까지 첨부할 수 있습니다.</div><div className="upload-actions"><label className="upload blue">📷<b>현장 사진 촬영</b><input hidden type="file" accept="image/*" capture="environment" onChange={e=>e.target.files?.[0]&&setFiles(x=>[...x,e.target.files![0].name].slice(0,5))}/></label><label className="upload">📁<b>파일 선택</b><input hidden type="file" multiple onChange={e=>setFiles(Array.from(e.target.files??[]).slice(0,5).map(f=>f.name))}/></label></div><h2>첨부 파일 ({files.length}/5)</h2>{files.length?files.map((f,i)=><div className="file-row" key={f}><span>📎 {f}</span><button onClick={()=>setFiles(x=>x.filter((_,n)=>n!==i))}>삭제</button></div>):<div className="empty">첨부파일은 선택 사항입니다.</div>}<button className="primary wide" onClick={()=>setPage("confirm")}>첨부 완료</button></section></main>;
 if(page==="confirm"&&pending)return <main className="shell"><Header title="보고서 제출 확인" onBack={()=>setPage("attach")}/><section className="card space center"><div className="success">✓</div><h2>입력 내용을 확인해 주세요.</h2><p className="muted">최종 제출 후 팀장 검토가 시작됩니다.</p><dl className="summary"><dt>업무 일자</dt><dd>{pending.work_date}</dd><dt>제목</dt><dd>{pending.title}</dd><dt>업무 유형</dt><dd>{pending.work_type==="office"?"사무":"제조·생산"}</dd><dt>진척도</dt><dd>{pending.progress}%</dd><dt>첨부파일</dt><dd>{files.length}개</dd></dl><div className="toolbar"><button className="secondary" onClick={()=>setPage("new")}>수정하기</button><button className="primary" onClick={submit}>최종 제출</button></div></section></main>;
 if(page==="review"&&selected)return <main className="shell"><Header title="보고서 검토" onBack={()=>setPage("reports")}/><section className="card space"><div className="person"><div className="avatar">김</div><div><h2>{selected.author_name}</h2><p>{selected.department}</p></div></div><div className="step">✓ 보고서 제출 <span>→</span> <b>2 검토 중</b> <span>→</span> 3 검토 완료</div><ReportBody r={selected}/><label className="form-label">검토 의견<textarea placeholder="검토 의견을 입력하세요."/></label><div className="toolbar sticky-actions"><button className="warn" onClick={()=>decide("revision_requested")}>보완 요청</button><button className="primary" onClick={()=>decide("approved")}>승인</button></div></section></main>;
 if(page==="detail"&&selected)return <main className="shell"><Header title={selected.title} sub={`${selected.work_date} · ${selected.author_name}`} onBack={()=>setPage("reports")}/><section className="card space"><Badge status={selected.status}/><ReportBody r={selected}/>{selected.feedback&&<div className="notice orange"><b>팀장 검토 의견</b><br/>{selected.feedback}</div>}<div className="toolbar"><button className="secondary" onClick={()=>pdf(selected)}>PDF 다운로드</button>{selected.status==="revision_requested"&&<button className="primary" onClick={()=>{setPending(selected);setPage("new")}}>보완 작성</button>}</div></section></main>;
 if(page==="admin")return <main className="shell"><Header title="관리자 현황판"/><section className="grid stats"><Stat label="전체 직원" value="128명"/><Stat label="오늘 제출" value="84명"/><Stat label="미제출" value="28명"/><Stat label="보완 요청" value="16건" accent/></section><section className="card space"><h2>부서별 제출률</h2><div className="bars">{[["기획팀",95],["개발팀",88],["영업팀",76],["디자인팀",60],["관리팀",32]].map(([n,v])=><div key={String(n)}><span style={{height:`${Number(v)*1.4}px`}}/><b>{v}%</b><small>{n}</small></div>)}</div><h2>직원별 현황</h2>{reports.map(r=><div className="report" key={r.id} onClick={()=>open(r)}><span><b>{r.author_name}</b><small>{r.department}</small></span><Badge status={r.status}/></div>)}</section><BottomNav page={page} role={role} onGo={setPage}/></main>;
 if(page==="alerts")return <main className="shell"><Header title="알림"/><section className="card space"><div className="tabs"><button className="active">전체</button><button>읽지 않음</button></div>{alerts.map(a=><article className="alert-row" key={a.id} onClick={()=>setAlerts(x=>x.map(i=>i.id===a.id?{...i,read:true}:i))}><div className={`alert-icon ${a.kind}`}>{a.kind==="revision"?"!":a.kind==="approved"?"✓":"↑"}</div><div><Badge status={a.kind==="revision"?"revision_requested":a.kind==="approved"?"approved":"submitted"}/><h3>{a.title}</h3><p>{a.message}</p><small>{a.time}</small></div>{!a.read&&<i className="unread"/>}</article>)}<button className="secondary wide" onClick={()=>setAlerts(x=>x.map(a=>({...a,read:true})))}>모두 읽음</button></section><BottomNav page={page} role={role} onGo={setPage}/></main>;
 return <main className="shell"><Header title="스마트 일일 업무" sub={role==="leader"?"팀장님, 검토할 보고서를 확인하세요.":"김민수님, 오늘도 좋은 하루 되세요."}/>{!isConfigured&&<div className="demo-ribbon">데모 모드 · 브라우저에 저장됩니다</div>}{page==="profile"?<section className="card space"><h2>내 정보</h2><p>김민수 · 생산1팀 · {role==="leader"?"팀장":"직원"}</p><button className="secondary" onClick={()=>setPage("login")}>로그아웃</button></section>:<><section className="grid stats"><Stat label="검토 대기" value={`${counts.submitted}건`}/><Stat label="보완 요청" value={`${counts.revision}건`} accent/><Stat label="승인 완료" value={`${counts.approved}건`}/><Stat label="이번 달" value={`${reports.length}건`}/></section>{page==="home"&&<section className="actions"><button className="primary" onClick={()=>setPage("new")}>＋ 오늘 보고서 작성</button><button className="secondary" onClick={()=>setPage("reports")}>전체 보고서 보기</button></section>}<section className="list"><div className="list-head"><h2>{page==="reports"?"내 보고서":"최근 보고서"}</h2>{page==="reports"&&<input className="search" placeholder="보고서 검색"/>}</div><div className="card">{reports.map(r=><article className="report" key={r.id} onClick={()=>open(r)}><div><b>{r.title}</b><small>{r.work_date} · {r.department} · {r.progress}%</small></div><Badge status={r.status}/></article>)}</div></section></>}<BottomNav page={page} role={role} onGo={setPage}/></main>;
}
function Stat({label,value,accent}:{label:string;value:string;accent?:boolean}){return <div className={`card stat ${accent?"accent":""}`}><span>{label}</span><b>{value}</b></div>}
function ReportBody({r}:{r:Report}){return <div className="report-body"><h3>완료 업무</h3><p>{r.completed}</p><h3>진행 업무 ({r.progress}%)</h3><div className="progress"><span style={{width:`${r.progress}%`}}/></div><p>{r.in_progress||"없음"}</p><h3>문제 및 조치</h3><p>{r.issues||"없음"}</p><p>{r.actions||"조치 없음"}</p><h3>다음 계획</h3><p>{r.next_plan||"없음"}</p></div>}
