"use client";
import {useEffect,useMemo,useState} from "react";
import type {User} from "@supabase/supabase-js";
import {getSupabase} from "@/lib/supabase";
import {isManager,type Role} from "@/lib/types";

type Profile={id:string;name:string;company:string;department:string;role:Role};
type Project={id:string;name:string;description:string;company:string;department:string;owner_id:string;created_by:string;start_date:string|null;due_date:string|null;progress:number;status:"planning"|"in_progress"|"on_hold"|"completed";priority:"low"|"normal"|"high"|"critical";updated_at:string};
type Update={id:string;project_id:string;user_id:string;update_date:string;progress:number;progress_summary:string;actions:string;issues:string;next_steps:string;created_at:string};
const supabase=getSupabase()!;
const empty={name:"",description:"",start_date:"",due_date:"",progress:0,status:"planning" as Project["status"],priority:"normal" as Project["priority"]};
export default function ProjectsApp(){
 const [user,setUser]=useState<User|null>(null),[profile,setProfile]=useState<Profile|null>(null),[projects,setProjects]=useState<Project[]>([]),[updates,setUpdates]=useState<Update[]>([]),[selected,setSelected]=useState<Project|null>(null),[form,setForm]=useState(empty),[note,setNote]=useState({progress:0,progress_summary:"",actions:"",issues:"",next_steps:""}),[message,setMessage]=useState(""),[busy,setBusy]=useState(true),[showNew,setShowNew]=useState(false),[q,setQ]=useState("");
 useEffect(()=>{supabase.auth.getUser().then(({data})=>{setUser(data.user);if(data.user)void load(data.user);else setBusy(false)})},[]);
 async function load(current:User){setBusy(true);setMessage("");const {data:p,error:pe}=await supabase.from("profiles").select("id,name,company,department,role").eq("id",current.id).single();if(pe||!p){setMessage("프로필을 불러오지 못했습니다.");setBusy(false);return}setProfile(p as Profile);const {data:ps,error}=await supabase.from("projects").select("*").order("updated_at",{ascending:false});if(error)setMessage(`프로젝트 조회 실패: ${error.message}`);setProjects((ps??[]) as Project[]);setBusy(false)}
 async function createProject(){if(!user||!profile||!form.name.trim())return;setBusy(true);const {error}=await supabase.from("projects").insert({name:form.name.trim(),description:form.description.trim(),company:profile.company,department:profile.department,owner_id:user.id,created_by:user.id,start_date:form.start_date||null,due_date:form.due_date||null,progress:form.progress,status:form.status,priority:form.priority});setBusy(false);if(error){setMessage(`프로젝트 저장 실패: ${error.message}`);return}setForm(empty);setShowNew(false);setMessage("프로젝트를 만들었습니다.");await load(user)}
 async function openProject(p:Project){setSelected(p);setNote({progress:p.progress,progress_summary:"",actions:"",issues:"",next_steps:""});const {data}=await supabase.from("project_updates").select("*").eq("project_id",p.id).order("update_date",{ascending:false}).order("created_at",{ascending:false});setUpdates((data??[]) as Update[])}
 async function saveUpdate(){if(!user||!selected)return;const {error}=await supabase.from("project_updates").insert({project_id:selected.id,user_id:user.id,progress:note.progress,progress_summary:note.progress_summary,actions:note.actions,issues:note.issues,next_steps:note.next_steps});if(error){setMessage(`추진사항 저장 실패: ${error.message}`);return}const status=note.progress>=100?"completed":selected.status==="planning"?"in_progress":selected.status;await supabase.from("projects").update({progress:note.progress,status,updated_at:new Date().toISOString()}).eq("id",selected.id);setMessage("프로젝트 추진사항을 저장했습니다.");await openProject({...selected,progress:note.progress,status});await load(user)}
 const list=useMemo(()=>projects.filter(p=>!q||`${p.name} ${p.description} ${p.department}`.toLowerCase().includes(q.toLowerCase())),[projects,q]);
 if(busy)return <main className="shell"><section className="card space"><h2>주요 프로젝트</h2><p>프로젝트 정보를 불러오는 중...</p></section></main>;
 if(!user)return <main className="shell"><section className="card space"><h2>로그인이 필요합니다</h2><p>먼저 ‘일일 업무 보고’ 화면에서 로그인해 주세요.</p></section></main>;
 if(selected)return <main className="shell"><header className="top compact"><button className="back" onClick={()=>setSelected(null)}>←</button><h1>{selected.name}</h1></header><section className="card space"><div className="toolbar"><span className="badge submitted">{projectStatus(selected.status)}</span><span className="badge draft">진행률 {selected.progress}%</span></div><p>{selected.description||"프로젝트 설명이 없습니다."}</p><p><b>기간</b> {selected.start_date||"미정"} ~ {selected.due_date||"미정"}</p><div className="progress-track"><div className="progress-bar" style={{width:`${selected.progress}%`}}/></div><h3>진행 현황 / 추진 사항 기록</h3><label>진행률 {note.progress}%<input type="range" min="0" max="100" value={note.progress} onChange={e=>setNote(x=>({...x,progress:Number(e.target.value)}))}/></label><label>현재 진행 현황<textarea value={note.progress_summary} onChange={e=>setNote(x=>({...x,progress_summary:e.target.value}))} placeholder="현재까지 진행된 내용을 작성하세요"/></label><label>이번 추진 사항<textarea value={note.actions} onChange={e=>setNote(x=>({...x,actions:e.target.value}))} placeholder="오늘 또는 이번 주에 추진한 사항"/></label><label>문제점 / 지연 사유<textarea value={note.issues} onChange={e=>setNote(x=>({...x,issues:e.target.value}))}/></label><label>다음 추진 계획<textarea value={note.next_steps} onChange={e=>setNote(x=>({...x,next_steps:e.target.value}))}/></label><button className="primary wide" onClick={()=>void saveUpdate()}>추진사항 저장</button>{message&&<p className="notice">{message}</p>}</section><section className="card space"><h3>추진 이력</h3>{updates.length?updates.map(u=><article className="project-update" key={u.id}><b>{u.update_date} · {u.progress}%</b><p>{u.progress_summary||"진행 현황 없음"}</p>{u.actions&&<p><b>추진:</b> {u.actions}</p>}{u.issues&&<p><b>문제:</b> {u.issues}</p>}{u.next_steps&&<p><b>다음:</b> {u.next_steps}</p>}</article>):<p className="empty">아직 등록된 추진 이력이 없습니다.</p>}</section></main>;
 return <main className="shell"><header className="top compact"><h1>주요 프로젝트 관리</h1></header>{message&&<div className="demo-ribbon">{message}</div>}<section className="card space"><div className="toolbar"><input placeholder="프로젝트 검색" value={q} onChange={e=>setQ(e.target.value)}/>{profile&&isManager(profile.role)&&<button className="primary" onClick={()=>setShowNew(v=>!v)}>＋ 프로젝트</button>}</div>{showNew&&<div className="project-form"><label>프로젝트명<input value={form.name} onChange={e=>setForm(x=>({...x,name:e.target.value}))}/></label><label>설명<textarea value={form.description} onChange={e=>setForm(x=>({...x,description:e.target.value}))}/></label><div className="two"><label>시작일<input type="date" value={form.start_date} onChange={e=>setForm(x=>({...x,start_date:e.target.value}))}/></label><label>완료 예정일<input type="date" value={form.due_date} onChange={e=>setForm(x=>({...x,due_date:e.target.value}))}/></label></div><div className="two"><label>상태<select value={form.status} onChange={e=>setForm(x=>({...x,status:e.target.value as Project["status"]}))}><option value="planning">계획</option><option value="in_progress">진행중</option><option value="on_hold">보류</option><option value="completed">완료</option></select></label><label>우선순위<select value={form.priority} onChange={e=>setForm(x=>({...x,priority:e.target.value as Project["priority"]}))}><option value="low">낮음</option><option value="normal">보통</option><option value="high">높음</option><option value="critical">긴급</option></select></label></div><button className="primary wide" onClick={()=>void createProject()}>프로젝트 저장</button></div>}</section><section className="list"><div className="card">{list.length?list.map(p=><article className="report" key={p.id} onClick={()=>void openProject(p)}><div><b>{p.name}</b><small>{p.department||"부서 미지정"} · {projectStatus(p.status)} · {p.progress}%</small></div><span className="badge draft">{priorityLabel(p.priority)}</span></article>):<div className="empty">등록된 주요 프로젝트가 없습니다.</div>}</div></section></main>
}
function projectStatus(v:Project["status"]){return v==="planning"?"계획":v==="in_progress"?"진행중":v==="on_hold"?"보류":"완료"}
function priorityLabel(v:Project["priority"]){return v==="low"?"낮음":v==="normal"?"보통":v==="high"?"높음":"긴급"}
