"use client";
import {useEffect,useMemo,useState} from "react";
import type {User} from "@supabase/supabase-js";
import {getSupabase} from "@/lib/supabase";
import {isManager,isSystemAdmin,statusLabel,type Report,type Role,type Status} from "@/lib/types";
import ReportForm from "./ReportForm";

type Page="login"|"home"|"new"|"attach"|"confirm"|"reports"|"detail"|"review"|"admin"|"users"|"alerts"|"profile";
type Profile={id?:string;email?:string;name:string;company?:string;department:string;role:Role};
type Notice={id:string;title:string;message:string;created_at:string;read_at:string|null};
type Attachment={id:string;original_name:string;storage_path:string;mime_type:string;size_bytes:number};
const supabase=getSupabase()!;

export default function SupabaseApp(){
 const [user,setUser]=useState<User|null>(null),[profile,setProfile]=useState<Profile|null>(null),[reports,setReports]=useState<Report[]>([]),[profiles,setProfiles]=useState<Profile[]>([]),[notices,setNotices]=useState<Notice[]>([]),[attachments,setAttachments]=useState<Attachment[]>([]);
 const [page,setPage]=useState<Page>("login"),[selected,setSelected]=useState<Report|null>(null),[pending,setPending]=useState<Report|null>(null),[files,setFiles]=useState<File[]>([]),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(true),[query,setQuery]=useState(""),[statusFilter,setStatusFilter]=useState("all"),[feedback,setFeedback]=useState("");
 useEffect(()=>{supabase.auth.getUser().then(({data})=>{setUser(data.user);if(data.user)void load(data.user);else setBusy(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user??null));return()=>data.subscription.unsubscribe()},[]);
 async function load(current:User){
  setBusy(true);setMessage("");
  const {data:p,error:pe}=await supabase.from("profiles").select("id,name,company,department,role").eq("id",current.id).single();
  if(pe){setMessage(`프로필 불러오기 실패: ${pe.message}`);setBusy(false);return}
  const next={...(p as Profile),email:current.email??""};setProfile(next);
  const [{data:r,error:re},{data:n},{data:ps}]=await Promise.all([
   supabase.from("daily_reports").select("*").order("work_date",{ascending:false}),
   supabase.from("in_app_notifications").select("*").order("created_at",{ascending:false}),
   isSystemAdmin(next.role)?supabase.from("profiles").select("id,name,company,department,role").order("name"):Promise.resolve({data:[]})
  ]);
  if(re)setMessage(`보고서 불러오기 실패: ${re.message}`);
  setReports((r??[]).map((x:any)=>fromDb(x,next)));setNotices((n??[]) as Notice[]);setProfiles((ps??[]) as Profile[]);
  setPage(isManager(next.role)?"admin":"home");setBusy(false);
 }
 async function login(){setBusy(true);setMessage("");const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error){setMessage("로그인에 실패했습니다. 이메일과 비밀번호를 확인하세요.");setBusy(false);return}if(data.user){setUser(data.user);await load(data.user)}}
 async function signup(){setBusy(true);setMessage("");const {data,error}=await supabase.auth.signUp({email,password,options:{data:{name:"신규 사용자",department:"",company:""}}});setBusy(false);setMessage(error?`가입 실패: ${error.message}`:data.session?"가입 및 로그인되었습니다.":"가입되었습니다. 로그인해 주세요.")}
 async function resetPassword(){if(!email){setMessage("이메일을 먼저 입력하세요.");return}const {error}=await supabase.auth.resetPasswordForEmail(email);setMessage(error?`재설정 요청 실패: ${error.message}`:"비밀번호 재설정 메일을 보냈습니다.")}
 async function logout(){await supabase.auth.signOut();setUser(null);setProfile(null);setPage("login")}
 function stage(r:Report){setPending(r);if(r.status==="draft"){void saveDraft(r);return}setPage("attach")}
 async function saveDraft(r:Report){if(!user)return;setBusy(true);const {error}=await supabase.from("daily_reports").upsert({...toDb(r),user_id:user.id,status:"draft"});setBusy(false);if(error){setMessage(`저장 실패: ${error.message}`);return}setMessage("임시저장했습니다.");await load(user)}
 async function submit(){if(!user||!pending)return;setBusy(true);setMessage("제출 중...");const {error:first}=await supabase.from("daily_reports").upsert({...toDb(pending),user_id:user.id,status:"draft"});if(first){setMessage(`저장 실패: ${first.message}`);setBusy(false);return}
  for(const file of files){if(file.size>10485760){setMessage(`${file.name}: 10MB를 초과했습니다.`);setBusy(false);return}const path=`${user.id}/${pending.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;const {error:up}=await supabase.storage.from("report-files").upload(path,file,{contentType:file.type,upsert:false});if(up){setMessage(`파일 업로드 실패: ${up.message}`);setBusy(false);return}const {error:meta}=await supabase.from("report_attachments").insert({report_id:pending.id,user_id:user.id,original_name:file.name,storage_path:path,mime_type:file.type||"application/octet-stream",size_bytes:file.size});if(meta){await supabase.storage.from("report-files").remove([path]);setMessage(`파일 정보 저장 실패: ${meta.message}`);setBusy(false);return}}
  const {error}=await supabase.from("daily_reports").update({status:"submitted",submitted_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",pending.id);setBusy(false);if(error){setMessage(`제출 실패: ${error.message}`);return}setPending(null);setFiles([]);setMessage("보고서를 제출했습니다.");await load(user)
 }
 async function openReport(r:Report,review=false){setSelected(r);setFeedback("");const {data}=await supabase.from("report_attachments").select("id,original_name,storage_path,mime_type,size_bytes").eq("report_id",r.id);setAttachments((data??[]) as Attachment[]);setPage(review?"review":"detail")}
 async function openAttachment(a:Attachment){const {data,error}=await supabase.storage.from("report-files").createSignedUrl(a.storage_path,60);if(error||!data){setMessage("첨부파일을 열 수 없습니다.");return}window.open(data.signedUrl,"_blank","noopener,noreferrer")}
 async function decide(status:"approved"|"revision_requested"){if(!user||!selected)return;const comment=feedback.trim()||(status==="approved"?"확인했습니다. 수고하셨습니다.":"내용을 보완한 뒤 재제출해 주세요.");const {error:f}=await supabase.from("report_feedback").insert({report_id:selected.id,reviewer_id:user.id,decision:status,comment});if(f){setMessage(`검토 의견 저장 실패: ${f.message}`);return}const {error}=await supabase.from("daily_reports").update({status,approved_at:status==="approved"?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq("id",selected.id);if(error){setMessage(`상태 변경 실패: ${error.message}`);return}setMessage(status==="approved"?"승인 처리했습니다.":"보완 요청을 보냈습니다.");await load(user)}
 async function markRead(n:Notice){await supabase.from("in_app_notifications").update({read_at:new Date().toISOString()}).eq("id",n.id);if(user)await load(user)}
 function printReport(r:Report){const w=window.open("","_blank","width=900,height=1000");if(!w)return;w.document.write(`<html><head><meta charset="utf-8"><title>${escapeHtml(r.title)}</title><style>body{font-family:-apple-system,BlinkMacSystemFont,'Malgun Gothic',sans-serif;padding:40px;color:#111}h1{color:#0b2c4d;border-bottom:3px solid #2563eb;padding-bottom:14px}dt{font-weight:700;margin-top:18px}dd{margin:5px 0 0;white-space:pre-wrap}.meta{background:#f5f7fb;padding:16px;border-radius:10px}</style></head><body><h1>스마트 일일 업무 보고서</h1><div class="meta"><b>${escapeHtml(r.company||profile?.company||"")}</b><br>${escapeHtml(r.department)} · ${escapeHtml(r.author_name)}<br>업무일자 ${r.work_date} · 상태 ${statusLabel[r.status]}</div><h2>${escapeHtml(r.title)}</h2><dl><dt>오늘 완료한 업무</dt><dd>${escapeHtml(r.completed)}</dd><dt>진행 중인 업무 (${r.progress}%)</dt><dd>${escapeHtml(r.in_progress||"없음")}</dd><dt>문제 사항</dt><dd>${escapeHtml(r.issues||"없음")}</dd><dt>조치 내용</dt><dd>${escapeHtml(r.actions||"없음")}</dd><dt>다음 계획</dt><dd>${escapeHtml(r.next_plan||"없음")}</dd><dt>지원 요청</dt><dd>${escapeHtml(r.support_request||"없음")}</dd></dl><script>window.onload=()=>window.print()</script></body></html>`);w.document.close()}
 const filtered=useMemo(()=>reports.filter(r=>(statusFilter==="all"||r.status===statusFilter)&&(!query||`${r.title} ${r.author_name} ${r.department}`.toLowerCase().includes(query.toLowerCase()))),[reports,query,statusFilter]);
 if(busy)return <main className="login-page"><section className="login-hero"><div className="shield">✓</div><h1>스마트 일일 업무</h1><p>안전하게 연결하는 중...</p></section></main>;
 if(page==="login")return <Login {...{email,password,message,setEmail,setPassword,login,signup,resetPassword}}/>;
 if(page==="new")return <ReportForm initial={pending??undefined} onSave={stage} onCancel={()=>setPage("home")}/>;
 if(page==="attach")return <main className="shell"><Head title="사진·문서 첨부" back={()=>setPage("new")}/><section className="card space"><p className="notice orange">최대 5개, 파일당 10MB · 사진/PDF/일반 문서</p><div className="upload-actions"><label className="upload blue">📷<b>현장 사진 촬영</b><input hidden type="file" accept="image/*" capture="environment" onChange={e=>e.target.files?.[0]&&setFiles(x=>[...x,e.target.files![0]].slice(0,5))}/></label><label className="upload">📁<b>파일 선택</b><input hidden type="file" multiple onChange={e=>setFiles(Array.from(e.target.files??[]).filter(f=>f.size<=10485760).slice(0,5))}/></label></div>{files.map((f,i)=><div className="file-row" key={`${f.name}-${i}`}><span>{f.name}</span><button onClick={()=>setFiles(x=>x.filter((_,j)=>j!==i))}>삭제</button></div>)}<button className="primary wide" onClick={()=>setPage("confirm")}>작성 내용 확인</button></section></main>;
 if(page==="confirm"&&pending)return <main className="shell"><Head title="작성 내용 확인 및 제출" back={()=>setPage("attach")}/><section className="card space center"><div className="success">✓</div><h2>{pending.title}</h2><dl className="summary"><dt>업무 일자</dt><dd>{pending.work_date}</dd><dt>진척도</dt><dd>{pending.progress}%</dd><dt>첨부파일</dt><dd>{files.length}개</dd></dl>{message&&<p className="error">{message}</p>}<button className="primary wide" onClick={()=>void submit()}>최종 제출</button></section></main>;
 if((page==="detail"||page==="review")&&selected)return <main className="shell"><Head title={page==="review"?"관리자 검토 및 의견":selected.title} back={()=>setPage(page==="review"?"admin":"reports")}/><section className="card space"><Badge status={selected.status}/><p><b>{selected.author_name}</b> · {selected.department} · {selected.work_date}</p><h3>완료 업무</h3><p>{selected.completed}</p><h3>진행 업무 ({selected.progress}%)</h3><p>{selected.in_progress||"없음"}</p><h3>문제 및 조치</h3><p>{selected.issues||"없음"}</p><p>{selected.actions||"조치 없음"}</p><h3>다음 계획 / 지원 요청</h3><p>{selected.next_plan||"없음"}</p><p>{selected.support_request||"없음"}</p><h3>첨부파일</h3>{attachments.length?attachments.map(a=><button className="secondary wide" key={a.id} onClick={()=>void openAttachment(a)}>📎 {a.original_name}</button>):<p>첨부파일 없음</p>}<button className="secondary wide" onClick={()=>printReport(selected)}>PDF 저장/인쇄</button>{page==="review"&&<><label>관리자 의견<textarea value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="승인 또는 보완 사유를 입력하세요"/></label><div className="toolbar"><button className="warn" onClick={()=>void decide("revision_requested")}>보완 요청</button><button className="primary" onClick={()=>void decide("approved")}>승인</button></div></>}</section></main>;
 if(page==="alerts")return <main className="shell"><Head title="알림"/><section className="card space">{notices.length?notices.map(n=><article className="alert-row" key={n.id} onClick={()=>void markRead(n)}><div className="alert-icon">●</div><div><h3>{n.title}</h3><p>{n.message}</p><small>{new Date(n.created_at).toLocaleString("ko-KR")}</small></div>{!n.read_at&&<i className="unread"/>}</article>):<div className="empty">새 알림이 없습니다.</div>}</section><Nav page={page} role={profile?.role??"employee"} go={setPage}/></main>;
 if(page==="users")return <main className="shell"><Head title="사용자·권한 관리" back={()=>setPage("admin")}/><section className="card"><div className="report"><b>사용자</b><b>부서 / 권한</b></div>{profiles.map(p=><article className="report" key={p.id}><div><b>{p.name}</b><small>{p.company||"회사 미지정"}</small></div><div><b>{p.department||"부서 미지정"}</b><small>{roleLabel(p.role)}</small></div></article>)}</section><p className="notice">현재 운영 DB 정책상 권한 변경은 시스템 관리자용 서버 기능을 통해 적용하도록 제한되어 있습니다.</p></main>;
 const role=profile?.role??"employee",review=isManager(role);
 return <main className="shell"><Head title={page==="admin"?"관리자 보고서 현황판":page==="reports"?"내 보고서":"스마트 일일 업무"}/>{message&&<div className="demo-ribbon">{message}</div>}{page==="profile"?<section className="card space"><h2>{profile?.name}</h2><p>{user?.email} · {profile?.company} · {profile?.department} · {roleLabel(role)}</p><button className="secondary" onClick={()=>void logout()}>로그아웃</button></section>:<><section className="grid stats"><Stat label="제출 대기" value={reports.filter(r=>r.status==="submitted").length}/><Stat label="보완 요청" value={reports.filter(r=>r.status==="revision_requested").length}/><Stat label="승인 완료" value={reports.filter(r=>r.status==="approved").length}/><Stat label="전체" value={reports.length}/></section>{page==="home"&&<section className="actions"><button className="primary" onClick={()=>{setPending(null);setPage("new")}}>＋ 오늘 보고서 작성</button><button className="secondary" onClick={()=>setPage("reports")}>전체 보고서</button></section>}{(page==="reports"||page==="admin")&&<section className="card space"><input placeholder="제목·작성자·부서 검색" value={query} onChange={e=>setQuery(e.target.value)}/><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">전체 상태</option><option value="draft">임시저장</option><option value="submitted">제출</option><option value="revision_requested">보완 요청</option><option value="approved">승인 완료</option></select>{page==="admin"&&isSystemAdmin(role)&&<button className="secondary wide" onClick={()=>setPage("users")}>사용자·권한 관리</button>}</section>}<section className="list"><div className="card">{filtered.length?filtered.map(r=><article className="report" key={r.id} onClick={()=>void openReport(r,review&&page==="admin")}><div><b>{r.title}</b><small>{r.work_date} · {r.author_name} · {r.progress}%</small></div><Badge status={r.status}/></article>):<div className="empty">조건에 맞는 보고서가 없습니다.</div>}</div></section></>}<Nav page={page} role={role} go={setPage}/></main>;
}
function fromDb(x:any,p:Profile):Report{return{id:x.id,work_date:x.work_date,title:x.title,work_type:x.work_type,shift:x.shift,completed:x.completed,in_progress:x.in_progress,issues:x.issues,actions:x.actions,next_plan:x.next_plan,support_request:x.support_request,progress:x.progress,status:x.status as Status,author_name:x.author_name??p.name,department:x.department??p.department,company:x.company??p.company,updated_at:x.updated_at}}
function toDb(r:Report){const issuePrefix=r.issue_category&&r.issue_category!=="none"?`[${r.issue_category}] `:"";const result=r.action_result?`\n조치 결과: ${r.action_result}`:"";return{id:r.id,work_date:r.work_date,title:r.title,work_type:r.work_type,shift:r.shift,completed:r.completed,in_progress:r.in_progress,issues:`${issuePrefix}${r.issues}`.trim(),actions:`${r.actions}${result}`.trim(),next_plan:r.next_plan,support_request:r.support_request,progress:r.progress,updated_at:new Date().toISOString()}}
function Login(p:{email:string;password:string;message:string;setEmail:(v:string)=>void;setPassword:(v:string)=>void;login:()=>void;signup:()=>void;resetPassword:()=>void}){return <main className="login-page"><section className="login-hero"><div className="shield">✓</div><h1>스마트 일일 업무</h1><p>직원 보고부터 관리자 승인까지 한 곳에서</p></section><section className="login-card"><label>이메일<input type="email" value={p.email} onChange={e=>p.setEmail(e.target.value)}/></label><label>비밀번호<input type="password" value={p.password} onChange={e=>p.setPassword(e.target.value)}/></label>{p.message&&<p className="error">{p.message}</p>}<button className="primary wide" onClick={p.login}>로그인</button><button className="secondary wide" onClick={p.signup}>첫 계정 만들기</button><button className="secondary wide" onClick={p.resetPassword}>비밀번호 재설정</button></section></main>}
function Head({title,back}:{title:string;back?:()=>void}){return <header className="top compact">{back&&<button className="back" onClick={back}>←</button>}<h1>{title}</h1></header>}
function Badge({status}:{status:Status}){return <span className={`badge ${status}`}>{statusLabel[status]}</span>}
function Stat({label,value}:{label:string;value:number}){return <div className="card stat"><span>{label}</span><b>{value}건</b></div>}
function Nav({page,role,go}:{page:Page;role:Role;go:(p:Page)=>void}){const x:[Page,string][]=[[isManager(role)?"admin":"home","⌂ 홈"],["new","＋ 작성"],["reports","▤ 보고서"],["alerts","● 알림"],["profile","♙ 내 정보"]];return <nav className="nav">{x.map(([k,l])=><button key={k} className={page==k?"active":""} onClick={()=>go(k)}>{l}</button>)}</nav>}
function roleLabel(r:Role){return r==="employee"?"직원":r==="manager"||r==="leader"?"관리자":"시스템 관리자"}
function escapeHtml(s:string){return String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]||c))}
