"use client";
import {useEffect,useState} from "react";
import type {User} from "@supabase/supabase-js";
import {getSupabase} from "@/lib/supabase";
import {statusLabel,type Report,type Role,type Status} from "@/lib/types";
import ReportForm from "./ReportForm";

type Page="login"|"home"|"new"|"attach"|"confirm"|"reports"|"detail"|"review"|"admin"|"alerts"|"profile";
type Profile={name:string;department:string;role:Role};
type Notice={id:string;title:string;message:string;created_at:string;read_at:string|null};
const supabase=getSupabase()!;

export default function SupabaseApp(){
 const [user,setUser]=useState<User|null>(null);const [profile,setProfile]=useState<Profile|null>(null);const [reports,setReports]=useState<Report[]>([]);const [notices,setNotices]=useState<Notice[]>([]);const [page,setPage]=useState<Page>("login");const [selected,setSelected]=useState<Report|null>(null);const [pending,setPending]=useState<Report|null>(null);const [files,setFiles]=useState<File[]>([]);const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(true);
 useEffect(()=>{supabase.auth.getUser().then(({data})=>{setUser(data.user);if(data.user)void load(data.user);else setBusy(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user??null));return()=>data.subscription.unsubscribe()},[]);
 async function load(current:User){setBusy(true);const [{data:p},{data:r},{data:n}]=await Promise.all([supabase.from("profiles").select("name,department,role").eq("id",current.id).single(),supabase.from("daily_reports").select("*").order("work_date",{ascending:false}),supabase.from("in_app_notifications").select("*").order("created_at",{ascending:false})]);const next=(p??{name:current.email??"사용자",department:"",role:"employee"}) as Profile;setProfile(next);setReports((r??[]).map(x=>({...x,author_name:next.name,department:next.department,updated_at:x.updated_at} as Report)));setNotices(n??[]);setPage(next.role==="admin"?"admin":"home");setBusy(false)}
 async function login(){setBusy(true);setMessage("");const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error){setMessage(error.message);setBusy(false);return}if(data.user){setUser(data.user);await load(data.user)}}
 async function signup(){setBusy(true);setMessage("");const {data,error}=await supabase.auth.signUp({email,password,options:{data:{name:"신규 사용자",department:"",company:""}}});setBusy(false);if(error){setMessage(error.message);return}setMessage(data.session?"가입 및 로그인되었습니다.":"가입되었습니다. 이메일 인증 후 로그인하세요.")}
 async function logout(){await supabase.auth.signOut();setUser(null);setProfile(null);setPage("login")}
 function stage(r:Report){if(r.status==="draft"){void saveDraft(r);return}setPending(r);setPage("attach")}
 async function saveDraft(r:Report){if(!user)return;setBusy(true);const {error}=await supabase.from("daily_reports").upsert({...toDb(r),user_id:user.id,status:"draft"});setBusy(false);if(error){setMessage(error.message);return}await load(user)}
 async function submit(){if(!user||!pending)return;setBusy(true);const {error:first}=await supabase.from("daily_reports").upsert({...toDb(pending),user_id:user.id,status:"draft"});if(first){setMessage(first.message);setBusy(false);return}for(const file of files){const path=`${user.id}/${pending.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;const {error:up}=await supabase.storage.from("report-files").upload(path,file,{contentType:file.type,upsert:false});if(up){setMessage(`${file.name}: ${up.message}`);setBusy(false);return}const {error:meta}=await supabase.from("report_attachments").insert({report_id:pending.id,user_id:user.id,original_name:file.name,storage_path:path,mime_type:file.type||"application/octet-stream",size_bytes:file.size});if(meta){await supabase.storage.from("report-files").remove([path]);setMessage(meta.message);setBusy(false);return}}const {error}=await supabase.from("daily_reports").update({status:"submitted",submitted_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",pending.id);setBusy(false);if(error){setMessage(error.message);return}setPending(null);setFiles([]);await load(user)}
 async function decide(status:"approved"|"revision_requested"){if(!user||!selected)return;const comment=status==="approved"?"확인했습니다. 수고하셨습니다.":"문제 사항에 예상 완료 시간을 추가해 주세요.";const {error:f}=await supabase.from("report_feedback").insert({report_id:selected.id,reviewer_id:user.id,decision:status,comment});if(f){setMessage(f.message);return}const {error}=await supabase.from("daily_reports").update({status,approved_at:status==="approved"?new Date().toISOString():null}).eq("id",selected.id);if(error){setMessage(error.message);return}await load(user)}
 async function markRead(n:Notice){await supabase.from("in_app_notifications").update({read_at:new Date().toISOString()}).eq("id",n.id);if(user)await load(user)}
 if(busy)return <main className="login-page"><section className="login-hero"><div className="shield">✓</div><h1>스마트 일일 업무</h1><p>안전하게 연결하는 중...</p></section></main>;
 if(page==="login")return <Login email={email} password={password} message={message} setEmail={setEmail} setPassword={setPassword} login={login} signup={signup}/>;
 if(page==="new")return <ReportForm initial={pending??undefined} onSave={stage} onCancel={()=>setPage("home")}/>;
 if(page==="attach")return <main className="shell"><Head title="사진·문서 첨부" back={()=>setPage("new")}/><section className="card space"><p className="notice orange">최대 5개, 파일당 10MB</p><div className="upload-actions"><label className="upload blue">📷<b>현장 사진 촬영</b><input hidden type="file" accept="image/*" capture="environment" onChange={e=>e.target.files?.[0]&&setFiles(x=>[...x,e.target.files![0]].slice(0,5))}/></label><label className="upload">📁<b>파일 선택</b><input hidden type="file" multiple onChange={e=>setFiles(Array.from(e.target.files??[]).filter(f=>f.size<=10485760).slice(0,5))}/></label></div>{files.map((f,i)=><div className="file-row" key={`${f.name}-${i}`}><span>{f.name}</span><button onClick={()=>setFiles(x=>x.filter((_,j)=>j!==i))}>삭제</button></div>)}<button className="primary wide" onClick={()=>setPage("confirm")}>첨부 완료</button></section></main>;
 if(page==="confirm"&&pending)return <main className="shell"><Head title="보고서 제출 확인" back={()=>setPage("attach")}/><section className="card space center"><div className="success">✓</div><h2>{pending.title}</h2><dl className="summary"><dt>업무 일자</dt><dd>{pending.work_date}</dd><dt>진척도</dt><dd>{pending.progress}%</dd><dt>첨부파일</dt><dd>{files.length}개</dd></dl>{message&&<p className="error">{message}</p>}<button className="primary wide" onClick={()=>void submit()}>최종 제출</button></section></main>;
 if((page==="detail"||page==="review")&&selected)return <main className="shell"><Head title={page==="review"?"보고서 검토":selected.title} back={()=>setPage("reports")}/><section className="card space"><Badge status={selected.status}/><h3>완료 업무</h3><p>{selected.completed}</p><h3>진행 업무 ({selected.progress}%)</h3><p>{selected.in_progress||"없음"}</p><h3>문제 및 조치</h3><p>{selected.issues||"없음"}</p><p>{selected.actions||"조치 없음"}</p>{page==="review"&&<div className="toolbar"><button className="warn" onClick={()=>void decide("revision_requested")}>보완 요청</button><button className="primary" onClick={()=>void decide("approved")}>승인</button></div>}</section></main>;
 if(page==="alerts")return <main className="shell"><Head title="알림"/><section className="card space">{notices.map(n=><article className="alert-row" key={n.id} onClick={()=>void markRead(n)}><div className="alert-icon">●</div><div><h3>{n.title}</h3><p>{n.message}</p><small>{new Date(n.created_at).toLocaleString("ko-KR")}</small></div>{!n.read_at&&<i className="unread"/>}</article>)}</section><Nav page={page} role={profile?.role??"employee"} go={setPage}/></main>;
 const role=profile?.role??"employee";const review=role==="leader"||role==="admin";
 return <main className="shell"><Head title={page==="admin"?"관리자 현황판":page==="reports"?"내 보고서":"스마트 일일 업무"}/>{message&&<div className="demo-ribbon">{message}</div>}{page==="profile"?<section className="card space"><h2>{profile?.name}</h2><p>{user?.email} · {profile?.department} · {role}</p><button className="secondary" onClick={()=>void logout()}>로그아웃</button></section>:<><section className="grid stats"><Stat label="검토 대기" value={reports.filter(r=>r.status==="submitted").length}/><Stat label="보완 요청" value={reports.filter(r=>r.status==="revision_requested").length}/><Stat label="승인 완료" value={reports.filter(r=>r.status==="approved").length}/><Stat label="전체" value={reports.length}/></section>{page==="home"&&<section className="actions"><button className="primary" onClick={()=>setPage("new")}>＋ 오늘 보고서 작성</button><button className="secondary" onClick={()=>setPage("reports")}>전체 보고서</button></section>}<section className="list"><div className="card">{reports.length?reports.map(r=><article className="report" key={r.id} onClick={()=>{setSelected(r);setPage(review?"review":"detail")}}><div><b>{r.title}</b><small>{r.work_date} · {r.progress}%</small></div><Badge status={r.status}/></article>):<div className="empty">등록된 보고서가 없습니다.</div>}</div></section></>}<Nav page={page} role={role} go={setPage}/></main>;
}
function toDb(r:Report){return{id:r.id,work_date:r.work_date,title:r.title,work_type:r.work_type,shift:r.shift,completed:r.completed,in_progress:r.in_progress,issues:r.issues,actions:r.actions,next_plan:r.next_plan,support_request:r.support_request,progress:r.progress,updated_at:new Date().toISOString()}}
function Login(p:{email:string;password:string;message:string;setEmail:(v:string)=>void;setPassword:(v:string)=>void;login:()=>void;signup:()=>void}){return <main className="login-page"><section className="login-hero"><div className="shield">✓</div><h1>스마트 일일 업무</h1><p>실제 Supabase 로그인</p></section><section className="login-card"><label>이메일<input type="email" value={p.email} onChange={e=>p.setEmail(e.target.value)}/></label><label>비밀번호<input type="password" value={p.password} onChange={e=>p.setPassword(e.target.value)}/></label>{p.message&&<p className="error">{p.message}</p>}<button className="primary wide" onClick={p.login}>로그인</button><button className="secondary wide" onClick={p.signup}>첫 계정 만들기</button></section></main>}
function Head({title,back}:{title:string;back?:()=>void}){return <header className="top compact">{back&&<button className="back" onClick={back}>←</button>}<h1>{title}</h1></header>}
function Badge({status}:{status:Status}){return <span className={`badge ${status}`}>{statusLabel[status]}</span>}
function Stat({label,value}:{label:string;value:number}){return <div className="card stat"><span>{label}</span><b>{value}건</b></div>}
function Nav({page,role,go}:{page:Page;role:Role;go:(p:Page)=>void}){const x:[Page,string][]=[["home","⌂ 홈"],["new","＋ 작성"],["reports","▤ 보고서"],["alerts","● 알림"],[role==="admin"?"admin":"profile",role==="admin"?"⚙ 관리":"♙ 내 정보"]];return <nav className="nav">{x.map(([k,l])=><button key={k} className={page==k?"active":""} onClick={()=>go(k)}>{l}</button>)}</nav>}
