create schema if not exists private;
create type public.app_role as enum ('employee','leader','admin');
create type public.report_status as enum ('draft','submitted','revision_requested','approved');
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,name text not null default '',company text not null default '',department text not null default '',role public.app_role not null default 'employee',leader_id uuid references public.profiles(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.daily_reports(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,work_date date not null,title text not null check(char_length(title) between 2 and 80),work_type text not null check(work_type in ('office','manufacturing')),shift text not null default '주간',completed text not null check(char_length(completed)>=2),in_progress text not null default '',issues text not null default '',actions text not null default '',next_plan text not null default '',support_request text not null default '',progress smallint not null default 0 check(progress between 0 and 100),status public.report_status not null default 'draft',submitted_at timestamptz,approved_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.report_attachments(id uuid primary key default gen_random_uuid(),report_id uuid not null references public.daily_reports(id) on delete cascade,user_id uuid not null references public.profiles(id) on delete cascade,original_name text not null,storage_path text not null unique,mime_type text not null,size_bytes bigint not null check(size_bytes>0 and size_bytes<=10485760),created_at timestamptz not null default now());
create table public.report_feedback(id uuid primary key default gen_random_uuid(),report_id uuid not null references public.daily_reports(id) on delete cascade,reviewer_id uuid not null references public.profiles(id) on delete cascade,decision public.report_status not null check(decision in ('revision_requested','approved')),comment text not null check(char_length(comment) between 1 and 2000),created_at timestamptz not null default now());
create table public.in_app_notifications(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,title text not null,message text not null,report_id uuid references public.daily_reports(id) on delete cascade,read_at timestamptz,created_at timestamptz not null default now());
create index daily_reports_user_date_idx on public.daily_reports(user_id,work_date desc);
create index daily_reports_status_date_idx on public.daily_reports(status,work_date desc);
create index profiles_leader_id_idx on public.profiles(leader_id) where leader_id is not null;
create index attachments_report_id_idx on public.report_attachments(report_id);
create index feedback_report_id_idx on public.report_feedback(report_id,created_at desc);
create index notifications_user_unread_idx on public.in_app_notifications(user_id,created_at desc) where read_at is null;
create function private.current_role() returns public.app_role language sql stable security definer set search_path='' as $$select p.role from public.profiles p where p.id=(select auth.uid())$$;
revoke all on function private.current_role() from public;
grant usage on schema private to authenticated;
grant execute on function private.current_role() to authenticated;
create function private.can_review(report_owner uuid) returns boolean language sql stable security definer set search_path='' as $$select coalesce(private.current_role()='admin' or (private.current_role()='leader' and exists(select 1 from public.profiles p where p.id=report_owner and p.leader_id=(select auth.uid()))),false)$$;
revoke all on function private.can_review(uuid) from public;
grant execute on function private.can_review(uuid) to authenticated;
create function private.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$begin insert into public.profiles(id,name,company,department) values(new.id,coalesce(new.raw_user_meta_data->>'name',''),coalesce(new.raw_user_meta_data->>'company',''),coalesce(new.raw_user_meta_data->>'department',''));return new;end;$$;
revoke all on function private.handle_new_user() from public;
create trigger on_auth_user_created after insert on auth.users for each row execute function private.handle_new_user();
alter table public.profiles enable row level security;
alter table public.daily_reports enable row level security;
alter table public.report_attachments enable row level security;
alter table public.report_feedback enable row level security;
alter table public.in_app_notifications enable row level security;
create policy profiles_select_scope on public.profiles for select to authenticated using(id=(select auth.uid()) or private.current_role()='admin' or leader_id=(select auth.uid()));
create policy profiles_update_own on public.profiles for update to authenticated using(id=(select auth.uid())) with check(id=(select auth.uid()));
create policy reports_select_scope on public.daily_reports for select to authenticated using(user_id=(select auth.uid()) or private.can_review(user_id));
create policy reports_insert_own on public.daily_reports for insert to authenticated with check(user_id=(select auth.uid()) and status in ('draft','submitted'));
create policy reports_update_own on public.daily_reports for update to authenticated using(user_id=(select auth.uid()) and status in ('draft','revision_requested')) with check(user_id=(select auth.uid()) and status in ('draft','submitted'));
create policy reports_delete_own_draft on public.daily_reports for delete to authenticated using(user_id=(select auth.uid()) and status='draft');
create policy reports_review_management on public.daily_reports for update to authenticated using(private.can_review(user_id) and status='submitted') with check(private.can_review(user_id) and status in ('revision_requested','approved'));
create policy attachments_select_scope on public.report_attachments for select to authenticated using(user_id=(select auth.uid()) or exists(select 1 from public.daily_reports r where r.id=report_id and private.can_review(r.user_id)));
create policy attachments_insert_own on public.report_attachments for insert to authenticated with check(user_id=(select auth.uid()) and exists(select 1 from public.daily_reports r where r.id=report_id and r.user_id=(select auth.uid()) and r.status in ('draft','revision_requested')));
create policy attachments_delete_own on public.report_attachments for delete to authenticated using(user_id=(select auth.uid()) and exists(select 1 from public.daily_reports r where r.id=report_id and r.status in ('draft','revision_requested')));
create policy feedback_select_scope on public.report_feedback for select to authenticated using(exists(select 1 from public.daily_reports r where r.id=report_id and (r.user_id=(select auth.uid()) or private.can_review(r.user_id))));
create policy feedback_insert_management on public.report_feedback for insert to authenticated with check(reviewer_id=(select auth.uid()) and exists(select 1 from public.daily_reports r where r.id=report_id and private.can_review(r.user_id)));
create policy notifications_select_own on public.in_app_notifications for select to authenticated using(user_id=(select auth.uid()));
create policy notifications_update_own on public.in_app_notifications for update to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
grant select,insert,update on public.profiles to authenticated;
grant select,insert,update,delete on public.daily_reports to authenticated;
grant select,insert,delete on public.report_attachments to authenticated;
grant select,insert on public.report_feedback to authenticated;
grant select,update on public.in_app_notifications to authenticated;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('report-files','report-files',false,10485760,array['image/jpeg','image/png','image/webp','application/pdf','text/plain','text/csv','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/vnd.ms-powerpoint','application/vnd.openxmlformats-officedocument.presentationml.presentation']);
create policy storage_insert_own_path on storage.objects for insert to authenticated with check(bucket_id='report-files' and (storage.foldername(name))[1]=(select auth.uid())::text);
create policy storage_select_scope on storage.objects for select to authenticated using(bucket_id='report-files' and ((storage.foldername(name))[1]=(select auth.uid())::text or exists(select 1 from public.report_attachments a join public.daily_reports r on r.id=a.report_id where a.storage_path=name and private.can_review(r.user_id))));
create policy storage_update_own on storage.objects for update to authenticated using(bucket_id='report-files' and (storage.foldername(name))[1]=(select auth.uid())::text) with check(bucket_id='report-files' and (storage.foldername(name))[1]=(select auth.uid())::text);
create policy storage_delete_own on storage.objects for delete to authenticated using(bucket_id='report-files' and (storage.foldername(name))[1]=(select auth.uid())::text);
